---
title: "Notes About Flutter Impeller Performances"
date: 2025-07-03T09:01:19+07:00
draft: false
---

I want to make this post as a reminder of myself about Flutter's Rendering Engine, Impeller. If you are a flutter develooper, you might already know or heard about new rendering engine named Impeller. As a successor of the previous one, Skia, this new rendering engine promised a better performances. 

As a developer who also often like to try new shining things, I also immideately jumped in when I knew new versions of flutter already released, I remember I am still using the 3.27.4 version of flutter but I still disabled the impeller engine, and the 3.29.0 came out and I upgraded my flutter sdk. At that time I was developing my [app](https://play.google.com/store/apps/details?id=com.aplikasihebat.baca_app) which already publised on Google Play Store and running smoothly on my device and have quite low crash rate. After I upgraded to 3.29.0, fortunately I didn't published it right away to play store, I noticed stutter in the UI. So I revert back to 3.27.4 version with impeller disabled and things running smoothly until now.

At third July 2025 I got a notification from Google Play Dashboard that I need to upgrade my In App Billing library to version 7.0 at minimum and also to target android with minimum API of 23. At first I thought that I have to upgrade my flutter SDK also. Then I checked into flutter sdk releases page and noticed that the already have newer version that 3.29, the latest was 3.32. I thought to myself, it this part of the reasons why Google asked us to upgrade because they have new versions of flutted SDK, and hopefuly already solve the impeller performance issues. So I upgraded again my flutter sdk into the latest version, it was 3.32.5 and tried to use the impeller engine but, again I still get the poor performances espsecially when using [Flame Engine](https://docs.flame-engine.org/latest/). I noticed that for some menus in my App that only using flutter, the performance was Ok i guess, but with menus using flame I saw jank and stutter in my UI. 

But my problems still remains, I am yet to upgrade my in app billing library and minimum API target. I thought that flutter SDK versions correlated with Android API version it can support or compile to. It turned out that I was wrong, I still able to change my build.gradel to target the minimum required Android API at 23, and still able to upgrade the in app billing library at version 7. So with this lesson it will be difficult for me to keep developing with flutter if their newest version have poor performances, although I really love working with flutter, but I hope the best for the future.
