baseURL = 'https://aplikasihebat.com/blog'
publishDir = "public/blog/"
languageCode = 'en-us'
title = 'Blog Aplikasi Hebat'
theme = ["PaperMod"] 
copyright = "@AplikasiHebat"
# Code Highlight

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Tulisan-tulisanku"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/zarkasy"


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

builddrafts = true

googleAnalytics = "G-KZEXBPVEMZ"