// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx5m9HB6CcDvWJ9WiBNWwC5xzygA-odgY',
    appId: '1:66416285908:web:0d6f14eccebca603f04341',
    messagingSenderId: '66416285908',
    projectId: 'belajarmembaca-59700',
    authDomain: 'belajarmembaca-59700.firebaseapp.com',
    storageBucket: 'belajarmembaca-59700.firebasestorage.app',
    measurementId: 'G-KQKBFY49NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYW8XOlijCXXHIrjRZ-JYj9BW3Z109XgE',
    appId: '1:66416285908:android:a2f6ecfe1f3c6723f04341',
    messagingSenderId: '66416285908',
    projectId: 'belajarmembaca-59700',
    storageBucket: 'belajarmembaca-59700.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAQbeZ60rxHNl9M-d6iBPMd9mzRIuGRE0',
    appId: '1:66416285908:ios:17fb0332bfaff401f04341',
    messagingSenderId: '66416285908',
    projectId: 'belajarmembaca-59700',
    storageBucket: 'belajarmembaca-59700.firebasestorage.app',
    iosBundleId: 'com.example.aplikasihebatHomepage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAQbeZ60rxHNl9M-d6iBPMd9mzRIuGRE0',
    appId: '1:66416285908:ios:17fb0332bfaff401f04341',
    messagingSenderId: '66416285908',
    projectId: 'belajarmembaca-59700',
    storageBucket: 'belajarmembaca-59700.firebasestorage.app',
    iosBundleId: 'com.example.aplikasihebatHomepage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx5m9HB6CcDvWJ9WiBNWwC5xzygA-odgY',
    appId: '1:66416285908:web:35693a7ccb79cac2f04341',
    messagingSenderId: '66416285908',
    projectId: 'belajarmembaca-59700',
    authDomain: 'belajarmembaca-59700.firebaseapp.com',
    storageBucket: 'belajarmembaca-59700.firebasestorage.app',
    measurementId: 'G-SVGRCQY1ZF',
  );

}