# Workflow to build and deploy site to Github Pages using Hugo

# Name of Workflow
name: github pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Step 2 - Sets up the latest version of Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.133.1"

      #Step 3 - Clean and don't fail
      - name: Clean public directory
        run: rm -rf public

      # Step 4 - Builds the site using the latest version of Hugo
      # Also specifies the theme we want to use
      - name: Build
        run: hugo --theme=PaperMod

      - name: "Install Flutter and Dart SDK"
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
          cache: true
          # flutter-version-file: aplikasihebat_homepage/pubspec.yaml
      - run: flutter pub get
        working-directory: aplikasihebat_homepage
      - run: flutter build web -o ../public/
        working-directory: aplikasihebat_homepage

      - name: Copy file CNAME
        uses: canastro/copy-file-action@master
        with:
          source: "public/blog/CNAME"
          target: "public/CNAME"

      - name: Copy file app-ads.txt
        uses: canastro/copy-file-action@master
        with:
          source: "public/blog/app-ads.txt"
          target: "public/app-ads.txt"

      # #Step 6 - Clean and don't fail
      # - name: Copy Belajar Baca App to public
      #   uses: andstor/copycat-action@v3
      #   with:
      #     personal_token: ${{ secrets.PERSONAL_TOKEN }}
      #     src_path: belajar-baca/
      #     dst_path: public/
      #     dst_owner: zarkasy
      #     dst_repo_name: zarkasy.github.io
      #Step 6 - Clean and don't fail
      - name: Copy Belajar Baca App to public
        run: cp -a /belajar-baca/. /public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
